#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-cython
Version  : 0.29.27
Release  : 126
URL      : https://files.pythonhosted.org/packages/eb/46/80dd9e5ad67ebc766ff3229901bde4a7bc82907efe93cd7007c4df458dd5/Cython-0.29.27.tar.gz
Source0  : https://files.pythonhosted.org/packages/eb/46/80dd9e5ad67ebc766ff3229901bde4a7bc82907efe93cd7007c4df458dd5/Cython-0.29.27.tar.gz
Summary  : The Cython compiler for writing C extensions for the Python language.
Group    : Development/Tools
License  : Apache-2.0 Python-2.0
Requires: pypi-cython-bin = %{version}-%{release}
Requires: pypi-cython-license = %{version}-%{release}
Requires: pypi-cython-python = %{version}-%{release}
Requires: pypi-cython-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : gdb
BuildRequires : pypi(coverage)
BuildRequires : pypi(ipython)
BuildRequires : pypi(numpy)
BuildRequires : python3-dev

%description
Welcome to Cython's documentation.
To build the documentation on Linux, you need Make and Sphinx installed on your system. Then execute::

%package bin
Summary: bin components for the pypi-cython package.
Group: Binaries
Requires: pypi-cython-license = %{version}-%{release}

%description bin
bin components for the pypi-cython package.


%package license
Summary: license components for the pypi-cython package.
Group: Default

%description license
license components for the pypi-cython package.


%package python
Summary: python components for the pypi-cython package.
Group: Default
Requires: pypi-cython-python3 = %{version}-%{release}

%description python
python components for the pypi-cython package.


%package python3
Summary: python3 components for the pypi-cython package.
Group: Default
Requires: python3-core
Provides: pypi(cython)

%description python3
python3 components for the pypi-cython package.


%prep
%setup -q -n Cython-0.29.27
cd %{_builddir}/Cython-0.29.27

%build
## build_prepend content
export LD_FLAGS="$LD_FLAGS -lgfortran"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643409018
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build  %{?_smp_mflags}

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cython
cp %{_builddir}/Cython-0.29.27/COPYING.txt %{buildroot}/usr/share/package-licenses/pypi-cython/38099d4531dd3d32b72df546041f15201123547f
cp %{_builddir}/Cython-0.29.27/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-cython/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cygdb
/usr/bin/cython
/usr/bin/cythonize

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cython/38099d4531dd3d32b72df546041f15201123547f
/usr/share/package-licenses/pypi-cython/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
